
// Define a mapping for weather condition codes
const WeatherCondition = {
    0: "Clear Night",
    1: "Cloudy",
    2: "Cold",
    3: "Flurries",
    4: "Fog",
    5: "Freezing Rain",
    6: "Hazy Moonlight",
    7: "Hazy Sunshine Day",
    8: "Hot",
    9: "Ice",
    10: "Intermittent Clouds Day",
    11: "Intermittent Clouds Night",
    12: "Mostly Clear Night",
    13: "Mostly Cloudy Day",
    14: "Mostly Cloudy Night",
    15: "Mostly Cloudy with Flurries Day",
    16: "Mostly Cloudy with Flurries Night",
    17: "Mostly Cloudy with Showers Day",
    18: "Mostly Cloudy with Showers Night",
    19: "Mostly Cloudy with Snow Day",
    20: "Mostly Cloudy with Snow Night",
    21: "Mostly Cloudy with Thunderstorms Day",
    22: "Mostly Cloudy with Thunderstorms Night",
    23: "Mostly Sunny Day",
    24: "Overcast",
    25: "Partly Cloudy Night",
    26: "Partly Cloudy with Showers Night",
    27: "Partly Cloudy with Thunderstorms Night",
    28: "Partly Sunny Day",
    29: "Partly Sunny with Flurries Day",
    30: "Partly Sunny with Showers Day",
    31: "Partly Sunny with Thunderstorms Day",
    32: "Rain",
    33: "Rain and Snow",
    34: "Showers",
    35: "Sleet",
    36: "Snow",
    37: "Sunny Day",
    38: "Thunderstorms",
    39: "Windy"
};

export default WeatherCondition;